connectors:
  aws:
    disable: true
  jira:
    skill: jira-agent-connector
    site_url: env:JIRA_SITE_URL
    email: env:JIRA_EMAIL
    api_token: env:JIRA_API_TOKEN
consumers:
  doc-wiki:
    enabled:
      - jira
